Change CI workflow for testing

diff --git a/.github/workflows/generate-documentation.yml b/.github/workflows/generate-documentation.yml
--- a/.github/workflows/generate-documentation.yml
+++ b/.github/workflows/generate-documentation.yml
@@ -1,6 +1,7 @@
 name: Generate Documentation
 
 on:
+  pull_request:
   release:
     types: [published]
 
@@ -46,8 +47,11 @@ jobs:
             echo "VERSION=$VERSION" >> "$GITHUB_ENV"
             echo "version=$VERSION" >> "$GITHUB_OUTPUT"
           else
-            echo "Error: runs on a tag only"
-            exit 1
+            echo "Version forced to 0.24.0"
+            echo "VERSION=0.24.0" >> "$GITHUB_ENV"
+            echo "version-0.24.0" >> "$GITHUB_OUTPUT"
+            # echo "Error: runs on a tag only"
+            # exit 1
           fi
       - name: Generate docs
         run: |
