Use POSIX-compliant logic for VERSION

diff --git a/.github/workflows/generate-documentation.yml b/.github/workflows/generate-documentation.yml
--- a/.github/workflows/generate-documentation.yml
+++ b/.github/workflows/generate-documentation.yml
@@ -36,17 +36,18 @@ jobs:
       - name: Extract version from GITHUB_REF
         id: set-version
         run: |
-          if [[ $GITHUB_REF == refs/tags/* ]]; then
-            echo "Tagged release"
-            # get last part of GITHUB_REF separated by /
-            VERSION=`echo $GITHUB_REF | tr '/' '\n' | tail -1`
-            echo "Version: $VERSION"
-            echo "VERSION=$VERSION" >> "$GITHUB_ENV"
-            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
-          else
-            echo "Error: runs on a tag only"
-            exit 1
-          fi
+          case "$GITHUB_REF" in
+            (refs/tags/*)
+              echo "Tagged release"
+              # get last part of GITHUB_REF separated by /
+              VERSION=`echo $GITHUB_REF | tr '/' '\n' | tail -1`
+              echo "Version: $VERSION" ;;
+              echo "VERSION=$VERSION" >> "$GITHUB_ENV"
+              echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+            (*)
+              echo "Error: runs on a tag only"
+              exit 1 ;;
+            esac
       - name: Generate docs
         run: |
           DOCS_BUCKET=${{ secrets.CD_API_REFS_BUCKET_NAME }} \
